### ISSUE TITLE
Graphiql broken in quickstart tutorial

### ISSUE THREAD

**Issue by mikeyjkmo** [tartiflette/tartiflette-starlette#41]
Follow the quickstart guide and navigating to http://localhost:8000 results in Graphiql crashing - it gets on "Loading". The javascript error is as follows:

```
Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://192.168.0.104:8000None' is invalid.
    at SubscriptionClient.connect (https://cdn.jsdelivr.net/npm/subscriptions-transport-ws@0.7.0/browser/client.js:1571:23)
    at new SubscriptionClient (https://cdn.jsdelivr.net/npm/subscriptions-transport-ws@0.7.0/browser/client.js:1314:18)
    at http://192.168.0.104:8000/:150:35
```

**Comment by florimondmanca** [comment]
Hey, thanks for reporting this! The traceback is very helpful.

It looks like the WebSocket endpoint URL is incorrectly passed as the “None” string instead of an empty string to the GraphiQL template when subscriptions aren’t enabled. I’ll give this a closer look very soon.

**Comment by mikeyjkmo** [comment]
@florimondmanca so looks like we're substituting None into the graphiql.html template, where it gets converted into a string.

```
    def render_template(                                                                                                                                                                                                                                                        
        self,                                                                                                                                                                                                                                                                   
        graphql_endpoint: str,                                                                                                                                                                                                                                                  
        subscriptions_endpoint: typing.Optional[str],                                                                                                                                                                                                                           
    ) -> str:                                                                                                                                                                                                                                                                   
        subscriptions_endpoint = (                                                                                                                                                                                                                                              
            "" if subscriptions_endpoint is None else subscriptions_endpoint                                                                                                                                                                                                    
        )                                                                                                                                                                                                                                                                       
        return self.template.substitute(                                                                                                                                                                                                                                        
            endpoint=graphql_endpoint,                                                                                                                                                                                                                                          
            subscriptions_endpoint=subscriptions_endpoint,                                                                                                                                                                                                                      
            default_query=self.default_query,                                                                                                                                                                                                                                   
            default_variables=json.dumps(self.default_variables),                                                                                                                                                                                                               
            default_headers=json.dumps(self.default_headers),                                                                                                                                                                                                                   
        ) 
```

Adding this if-statement fixes the issue.

**Comment by florimondmanca** [comment]
Sounds good. We may want to check that we correctly check against the empty string in the graphiql HTML file as well, and then it’s all good.

**Comment by mikeyjkmo** [comment]
The javascript appears to do a truthy test on the empty string, so looks okay to me.

**Comment by florimondmanca** [comment]
Released in 0.5.1. :+1:
